### ISSUE TITLE
extension folder location not quite right - possible typo?

### ISSUE THREAD

**Issue by appijumbo** [sambody/inkscape-guide-tools#5]
For the installation guide, the location of the extension folder in OS X should be

/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions

(and not /Applications/Inkscape.app/Contents/Resources/extensions) as in your current guide

At least thats what it seems to be in my iMac ...

Hope thats useful, 
Thanks

**Comment by su-v** [comment]
Ideally, install custom extensions as user extensions (see Inkscape menu 'Edit > Preferences > System' for details - this applies to all platforms!).

@appijumbo - packaging details changed between Inkscape 0.48 and Inkscape 0.91 for OS X (it's not mentioned in the release notes because regular users are not supposed to install custom extensions there ("there" = inside an application bundle installed with admin rights) - the location for user extensions is unchanged ( `$HOME/.config/inkscape/extensions/` on Linux and OS X, `%APPDATA%\inkscape\extensions\` on Windows).

**Comment by sambody** [comment]
I have updated the installation paths to use the prefered paths for user extensions. Thanks @su-v for that information.
